name: Restore App Service Plans

on:
  schedule:
    - cron: '0 2 * * 1' # Runs every Monday at 2 AM UTC
  workflow_dispatch:

jobs:
  restore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run PowerShell to Restore Plans
        shell: pwsh
        run: |
          ./scripts/AppServicePlanManager.ps1 -Action "Restore"
